apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
  labels:
    type: local
  namespace: machinamespace
spec:
  storageClassName: gp2
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: "vol-0f4062d1833c95166"
    fsType: ext4
