apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webapp
  namespace: machinamespace
  labels:
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend-container
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-end-service
  namespace: machinamespace
spec:
  selector:
    tier: frontend
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30084
  type: NodePort

