apiVersion: apps/v1
kind: Deployment
metadata:
  name: livireadiness-deploy
  namespace: machinamespace
  labels:
    app: livi
spec:
  selector:
    matchLabels:
      app: livi
  template:
    metadata:
      labels:
        app: livi
    spec:
      containers:
      - name: livi-container
        image: nginx
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            port: 80
            path: /index.html
          initialDelaySeconds: 15
          periodSeconds: 10

