apiVersion: v1
kind: Pod
metadata:
  name: nginx-resolver
  labels:
    app: sooraj
  namespace: machinamespace
spec:
  containers:
  - name: nginx-resolver-container
    image: nginx
    command:
    - sleep
    - "4800"
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-resolver-svc
  namespace: machinamespace
spec:
  selector:
    app: sooraj
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
