apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-alpine-deployment
  labels:
    app: nginx-alpine
  namespace: machinamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-alpine
  template:
    metadata:
      labels:
        app: nginx-alpine
    spec:
      containers:
      - name: nginx-aline-container
        image: nginx:alpine
        resources:
          requests:
            memory: "150Mi"
            cpu: "150m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        ports:
        - containerPort: 80




