apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-analytics
  namespace: machinamespace
  labels:
    type: local
spec:
  selector:
    matchLabels:
      type: local
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
