apiVersion: apps/v1
kind: Deployment
metadata:
  name: serverapp-deployment
  labels:
    app: server-app
  namespace: machinamespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-app
        image: machendra2612/server_app
        command:
        - sleep
        - "3600"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: serverapp-service
  namespace: machinamespace
spec:
  selector:
    app: server-app
  ports:
  - protocol: TCP
    port: 5000
  type: LoadBalancer
