apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: machinamespace
spec:
  containers:
  - name: jupiter
    image: nginx
    env:
    - name: planet
  - name: europa
    image: busybox
    command:
    - sleep
    - "4800"
    env:
    - name: moon
