apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
  namespace: machinamespace
spec:
  containers:
  - name: test-container
    image: nginx
    volumeMounts:
    - mountPath: /test-ebs
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: "vol-0f4062d1833c95166"
      fsType: ext4
